# Puerto del servidor
server:
  port: 8081
  error:
    whitelabel:
      enabled: false
    include-message: always
    include-binding-errors: always

# Nombre del servicio
spring:
  application:
    name: servicio-estudiantes
  
  # MongoDB - Atlas (Cloud)
  data:
    mongodb:
      uri: mongodb+srv://lopuaz909_db_user:ampkWIfWSf0AJ29u@universidad-cluster.airjh7v.mongodb.net/?appName=universidad-cluster
  
  # Jackson configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

# Logs útiles en desarrollo
logging:
  level:
    org.springframework.data.mongodb: DEBUG